#!/usr/bin/python
import sys
import mod_pbxproj
from mod_pbxproj import XcodeProject
from subprocess import call
projectDir = sys.argv[1]
scoreflexDir = projectDir + "/scoreflex"
call(["cp", "Assets/Plugins/Scoreflex/iOS/scoreflexBridge.m", projectDir + "/"])
call(["unzip", "-o", "Assets/Plugins/Scoreflex/iOS/scoreflex.zip", "-d", scoreflexDir])
project = XcodeProject.Load(sys.argv[1] + "/Unity-iPhone.xcodeproj/project.pbxproj")
group = project.get_or_create_group("Scoreflex")
project.add_file(projectDir + "/scoreflexBridge.m", parent=group)
project.add_file(scoreflexDir + "/libScoreflex.a", parent=group)
project.add_file(scoreflexDir + "/ScoreflexResources.bundle", parent=group)
project.add_file(scoreflexDir + "/include/Scoreflex/Scoreflex.h", parent=group)
project.add_file(scoreflexDir + "/include/Scoreflex/SXResponse.h", parent=group)
project.add_file(scoreflexDir + "/include/Scoreflex/SXview.h", parent=group)
project.save()
